
export const ERRORS = {
  ERROR_BOX_COUNT_OVER: "BOX_COUNT_OVER",
  ERROR_BOX_CLIENT_OVER: "BOX_CLIENT_OVER",
  ERROR_MEMBERID_ALREADY_USED: "MEMBERID_ALREADY_USED",
  ERROR_ALREADY_OPENED: "ALREADY_OPENED",
  ERROR_NOT_OPENED: "NOT_OPENED"
}
