/**
 * Every user-facing string in one place, so translating the demo is a matter
 * of adding a dictionary rather than hunting through components. English is
 * the source language; `es` is provided as a working second locale.
 */
export const en = {
  tagline:
    'Thermal receipt printing for Epson TM devices, from TypeScript. This demo runs against a simulated printer, so you can try all of it without hardware.',
  connection: 'Connection',
  demoMode: 'Demo mode — simulated printer, no hardware or network',
  address: 'Address',
  port: 'Port',
  connect: 'Connect',
  connecting: 'Connecting…',
  disconnect: 'Disconnect',
  remove: 'Remove',
  addPrinter: '+ Add another printer',
  recipes: 'Recipes',
  print: 'Print',
  showCode: 'Show code',
  hideCode: 'Hide code',
  inputs: 'Inputs',
  barcode: 'Barcode',
  symbol: '2D symbol',
  data: 'Data',
  status: 'Status',
  checkStatus: 'Check',
  startMonitoring: 'Monitor every 3s',
  stopMonitoring: 'Stop monitoring',
  online: 'Online',
  cover: 'Cover',
  paper: 'Paper',
  drawer: 'Drawer',
  open: 'open',
  closed: 'closed',
  yes: 'yes',
  no: 'no',
  activity: 'Activity',
  paperRail: 'Printed paper',
  nothingPrinted: 'Nothing printed yet.',
  nothingPrintedHint: 'Connect and run a recipe — the paper comes out here.',
  viewPaper: 'Paper',
  viewXml: 'XML',
  noJobId: 'no job id',
  ledReady: 'ready',
  ledPaper: 'paper',
  ledCover: 'cover',
  ledDrawer: 'drawer',
  rasterImage: 'raster image',
  drawerOpened: 'drawer opened',
  // log lines
  logConnectingSim: 'Connecting to the simulated printer…',
  logConnecting: (host: string, port: number) => `Connecting to ${host}:${port}…`,
  logConnectedSim: 'Connected (simulated). 8 sheets of paper loaded.',
  logConnected: 'Connected. Printer ready.',
  logConnectFailed: (reason: string) => `Could not connect: ${reason}`,
  logDisconnected: 'Disconnected.',
  logRunning: (what: string) => `${what}…`,
  logAttemptFailed: (attempt: number, reason: string) => `Attempt ${attempt} failed: ${reason}`,
  logStatus: (hex: string, battery: number) => `Status: 0x${hex} — battery: ${battery}`,
  logRetryLast: 'Retrying the last job',
  logRecovering: 'Running recover()…',
  logMonitoringOn: 'Monitoring started (every 3s).',
  logMonitoringOff: 'Monitoring stopped.',
};

export type Strings = typeof en;

export const es: Strings = {
  ...en,
  tagline:
    'Impresión térmica en equipos Epson TM, desde TypeScript. Esta demo corre contra una impresora simulada: podés probarla entera sin hardware.',
  connection: 'Conexión',
  demoMode: 'Modo demo — impresora simulada, sin hardware ni red',
  address: 'Dirección',
  port: 'Puerto',
  connect: 'Conectar',
  connecting: 'Conectando…',
  disconnect: 'Desconectar',
  remove: 'Quitar',
  addPrinter: '+ Agregar otra impresora',
  recipes: 'Recetas',
  print: 'Imprimir',
  showCode: 'Ver código',
  hideCode: 'Ocultar código',
  inputs: 'Datos',
  barcode: 'Código de barras',
  symbol: 'Símbolo 2D',
  data: 'Datos',
  status: 'Estado',
  checkStatus: 'Consultar',
  startMonitoring: 'Monitorear cada 3s',
  stopMonitoring: 'Detener monitoreo',
  online: 'En línea',
  cover: 'Tapa',
  paper: 'Papel',
  drawer: 'Cajón',
  open: 'abierto',
  closed: 'cerrado',
  yes: 'sí',
  no: 'no',
  activity: 'Actividad',
  paperRail: 'Papel impreso',
  nothingPrinted: 'Todavía no se imprimió nada.',
  nothingPrintedHint: 'Conectá y probá una receta — el papel sale por acá.',
  viewPaper: 'Papel',
  viewXml: 'XML',
  noJobId: 'sin job id',
  ledReady: 'listo',
  ledPaper: 'papel',
  ledCover: 'tapa',
  ledDrawer: 'cajón',
  rasterImage: 'imagen raster',
  drawerOpened: 'cajón abierto',
  logConnectingSim: 'Conectando a la impresora simulada…',
  logConnecting: (host: string, port: number) => `Conectando a ${host}:${port}…`,
  logConnectedSim: 'Conectado (simulada). 8 tickets de papel cargados.',
  logConnected: 'Conectado. Impresora lista.',
  logConnectFailed: (reason: string) => `No se pudo conectar: ${reason}`,
  logDisconnected: 'Desconectado.',
  logRunning: (what: string) => `${what}…`,
  logAttemptFailed: (attempt: number, reason: string) => `Intento ${attempt} falló: ${reason}`,
  logStatus: (hex: string, battery: number) => `Estado: 0x${hex} — batería: ${battery}`,
  logRetryLast: 'Reintentando el último trabajo',
  logRecovering: 'Ejecutando recover()…',
  logMonitoringOn: 'Monitoreo iniciado (cada 3s).',
  logMonitoringOff: 'Monitoreo detenido.',
};

/** Swap this to `es` (or wire it to navigator.language) to translate the demo. */
export const t: Strings = en;
